mux2to1.v
mux4to1.v
adder32.v
register32.v
program_counter.v
register_file.v
immediate_generator.v
alu.v
alu_control.v
main_control.v
branch_compare.v
instruction_memory.v
data_memory.v
load_store_unit.v
writeback_mux.v
forwarding_unit.v
hazard_detection_unit.v
next_pc_unit.v
branch_flush_unit.v
if_id_reg.v
id_ex_reg.v
ex_mem_reg.v
mem_wb_reg.v
